logInform corrected to login.ejs event listener
RojoRevolution/p2_org_decider pull request #91
Opened 2021-02-15 19:51 UTC by richardgabaree

2021-02-16 17:03 UTC, trevorsmithbanjo requested changes
Your password needs to be removed from the config.json and package.json.

2021-02-16 17:03 UTC, trevorsmithbanjo commented on config/config.json
> +    "password": "J@hntanious1",
This password should be removed.

2021-02-16 17:03 UTC, trevorsmithbanjo commented on package.json
> +  "description": "J@hntanious1",
It should be removed here as well.

2021-02-16 17:47 UTC, richardgabaree commented
I deleted and did another push


> On Feb 16, 2021, at 11:04 AM, Trevor Smith <notifications@github.com> wrote:
> 
> 
> @trevorsmithbanjo requested changes on this pull request.
> 
> Your password needs to be removed from the config.json and package.json.
> 
> In config/config.json <https://github.com/RojoRevolution/p2_org_decider/pull/91#discussion_r576985750>:
> 
> > @@ -1,7 +1,7 @@
>  {
>    "development": {
>      "username": "root",
> -    "password": "",
> +    "password": "J@hntanious1",
> This password should be removed.
> 
> In package.json <https://github.com/RojoRevolution/p2_org_decider/pull/91#discussion_r576985999>:
> 
> > @@ -1,7 +1,7 @@
>  {
>    "name": "p2_org_decider",
>    "version": "1.0.0",
> -  "description": "",
> +  "description": "J@hntanious1",
> It should be removed here as well.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/RojoRevolution/p2_org_decider/pull/91#pullrequestreview-591436284>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AR6L2KIPJ7KZEPRCIAGDNX3S7KQQXANCNFSM4XVHIFYQ>.
>

2021-02-17 16:20 UTC, trevorsmithbanjo approved these changes
👍🏻

2021-02-17 16:20 UTC, merged